name: Deploy

on:
  workflow_dispatch:

  repository_dispatch:
    types: [formatted]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup pnpm package manager
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: Build dist folder
        run: pnpm build

      - name: Publish dist to surge.sh
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: 'deaths.surge.sh'
          project: 'dist'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
