name: Format

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - 'src/**'

  pull_request:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: apt-get install pcregrep

      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'America/Chicago'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: Format code
        run: pnpm format

      - name: See if any code changed
        id: checkFiles
        run: echo ::set-output name=changed::$(git status --porcelain | wc -l)

      - name: Push changed code
        if: steps.checkFiles.outputs.changed > 0
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          files_changed=`git diff --stat | pcregrep -o '[0-9]+\sfiles?'`
          git add .
          git commit -m "formatted $files_changed"
          git push

      - name: Dispatch formatted
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: formatted
